### ISSUE TITLE
UNABLE TO SAVE POST ON SQLITE DATABASE FOR ISSO

### ISSUE THREAD

**Issue by mikemainz** [umputun/remark#387]
Hello,

Need guidance am at the edge of my wits; 

spawned uWSGI master process (pid: 4369)
spawned the uWSGI spooler on dir /opt/django/vbaraza/data/spool with pid 4373
spawned uWSGI worker 1 (pid: 4374, cores: 2)
cache sweeper thread enabled
[pid: 4374|app: 0|req: 1/1] 41.80.88.202 () {48 vars in 768 bytes} [Thu Jul 25 16:57:44 2019] OPTIONS /preview => generated 0 bytes in 1 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)
[pid: 4374|app: 0|req: 2/2] 41.80.88.202 () {50 vars in 1226 bytes} [Thu Jul 25 16:57:44 2019] POST /preview => generated 45 bytes in 29 msecs (HTTP/2.0 200) 7 headers in 349 bytes (1 switches on core 0)
[pid: 4374|app: 0|req: 3/3] 41.80.88.202 () {48 vars in 789 bytes} [Thu Jul 25 16:57:47 2019] OPTIONS /new?uri=%2Fblog%2F => generated 0 bytes in 0 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 1)
2019-07-25 16:57:47,750 ERROR: POST /new
Traceback (most recent call last):
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/__init__.py", line 141, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 92, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/__init__.py", line 46, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 282, in new
    thread = self.threads.new(uri, title)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/threads.py", line 33, in new
    "INSERT INTO threads (uri, title) VALUES (?, ?)", (uri, title))
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/__init__.py", line 62, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: unable to open database file
[pid: 4374|app: 0|req: 4/4] 41.80.88.202 () {50 vars in 1249 bytes} [Thu Jul 25 16:57:47 2019] POST /new?uri=%2Fblog%2F => generated 290 bytes in 4 msecs (HTTP/2.0 500) 7 headers in 362 bytes (1 switches on core 1)

**Comment by umputun** [comment]
you posted this to wrong project
